### ISSUE TITLE
Inconsistent intersection results for same shape based on method of creation

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#519] opened 2024-02-01 09:33 UTC
```py
r = (ShapeList() + (PolarLocations(1, 4) * Line((0,-1),(0,1)))).edges()
l = Line(1,2).edge()
i = l.intersect(*r)
```
<img width="331" alt="a" src="https://github.com/gumyr/build123d/assets/149267773/106cbc60-b029-4c84-b1f3-517ecd6a5396">

```py
r = Rectangle(2,2).edges()
l = (Pos(1) * Line(0,1)).edge()
i = l.intersect(*r)
```
<img width="331" alt="b" src="https://github.com/gumyr/build123d/assets/149267773/ef54fd60-4a10-4ac8-91fe-77b852055294">

**Comment by gumyr** [comment] 2024-02-01 23:07
Related to Issue #328

**Comment by bernhard-42** [comment] 2024-02-16 16:52
I think the issue is that after OCCT found the right intersection, the filter in `Edge.intersections` does a exact comparison instead of taking the tolerance again into account.

I think the following change should be applied:

![image](https://github.com/gumyr/build123d/assets/954408/dddd28c6-5ad0-4962-94b4-6ff2ad2e2b46)

**Comment by gumyr** [comment] 2024-02-22 19:25
Thanks @MatthiasJ1 and @bernhard-42, tolerance was indeed the problem, fixed now.

**Closed as completed by gumyr** 2024-02-22 19:25 UTC
Labels: bug
