### ISSUE TITLE
mirror should either fail with a hint or work as expected

### ISSUE THREAD

**Issue by OvisMaximus** [gumyr/build123d#207] opened 2023-04-08 13:05 UTC
```python
from build123d import *

clamp_width = 10.0
ring_width = 6
hose_radius = 2.15
clamp_height = 27.5

def create_solid()->BuildPart:
    with BuildPart(Plane.XZ) as clamp:
        with BuildSketch(Plane.XZ) as sketch_builder:
            with BuildLine(Plane.XZ) as shape:
                Polyline((ring_width, 0), (ring_width/2, clamp_height), (0, clamp_height), (0 ,0), close = True)
            make_face()
        mirror(sketch_builder.sketch, Plane.YZ)
        extrude(amount=clamp_width)
    return clamp


show_object(create_solid().part.wrapped)
```

creates

![Screenshot 2023-04-08 145534](https://user-images.githubusercontent.com/5701377/230722334-53979299-76fe-4519-8a78-956a97ca5cef.png)

To get the model to work, I had to call mirror() inside `with BuildSketch ...` and drop the first positional argument.

But: **it either should work as expected or raise an error.**

Secondly, the mirrored face is not only on the wrong plane, it also is the mirrored shape plus the bottom  shape of the solid.

May be an error caused by the issue observed in https://github.com/gumyr/build123d/issues/159

**Comment by gumyr** [comment] 2023-04-08 17:43
This is caused by a long-standing problem when inserting a face from Plane.XZ when all Sketch objects must reside on Plane.XY. It's fixed as of commit d3d05e691766540921cb82e6834734b96469fa25.
```py
def create_solid() -> BuildPart:
    with BuildPart(Plane.XZ) as clamp:
        with BuildSketch(Plane.XZ) as sketch_builder:
            with BuildLine(Plane.XZ) as shape:
                Polyline(
                    (ring_width, 0),
                    (ring_width / 2, clamp_height),
                    (0, clamp_height),
                    (0, 0),
                    close=True,
                )
            make_face()
            sketch = sketch_builder.sketch
            m = mirror(sketch_builder.sketch, Plane.YZ)
        extrude(amount=clamp_width)
    return clamp.part, sketch, m

c, s, m = create_solid()

show_object(c, name="clamp")
show_object(s, name="sketch")
show_object(m, name="m")
```
![image](https://user-images.githubusercontent.com/85638518/230735468-aa0a9e9a-778d-4d0b-83d3-024a49241cbc.png)

**Closed as completed by gumyr** 2023-04-08 17:43 UTC
Labels: bug
