### ISSUE TITLE
Support Path objects for import / export functions

### ISSUE THREAD

**Issue by lypwig** [gumyr/build123d#774] opened 2024-11-11 09:46 UTC
Python's builtin [pathlib](https://docs.python.org/3/library/pathlib.html) normalizes path functions with an object-oriented Path object.

I could be very practical if all import and export functions could support Path objects for each argument involving a path.

I can make a PR for this if you agree.

**Comment by KilowattSynthesis** [comment] 2024-11-11 13:20
Duplicate of #685. Seems that there was no objection when it was brought up earlier; a PR would be fantastic, I'm sure :)

**Comment by jdegenstein** [comment] 2024-11-11 13:56
@roipoussiere I support this idea, PR would be very welcome

**Comment by gumyr** [comment] 2024-11-11 15:11
+1

**Closed as completed** 2024-11-15 23:06 UTC
Labels: duplicate
